export default function useJobData() {

const items = [
  { name: 'Full Stack Developer'},
  { name: 'Front End Developer'},
  { name: 'Back End Developer'},
  { name: 'Account Manager'},
  { name: 'Accountant'},
  { name: 'Actor'},
  { name: 'Actuary'},
  { name: 'Adjustment Clerk'},
  { name: 'Admin'},
  { name: 'Administrative Law Judge'},
  { name: 'Administrative Services Manager'},
  { name: 'Administrative Support Supervisors'},
  { name: 'Advertising Manager OR Promotions Manager'},
  { name: 'Advertising Sales Agent'},
  { name: 'Aerospace Engineer'},
  { name: 'Agricultural Crop Farm Manager'},
  { name: 'Agricultural Crop Worker'},
  { name: 'Agricultural Engineer'},
  { name: 'Agricultural Equipment Operator'},
  { name: 'Agricultural Inspector'},
  { name: 'Agricultural Manager'},
  { name: 'Agricultural Product Grader Sorter'},
  { name: 'Agricultural Sales Representative'},
  { name: 'Agricultural Science Technician'},
  { name: 'Agricultural Sciences Teacher'},
  { name: 'Agricultural Technician'},
  { name: 'Agricultural Worker'},
  { name: 'Air Crew Member'},
  { name: 'Air Crew Officer'},
  { name: 'Air Traffic Controller'},
  { name: 'Aircraft Assembler'},
  { name: 'Aircraft Body Repairer'},
  { name: 'Aircraft Cargo Handling Supervisor'},
  { name: 'Aircraft Engine Specialist'},
  { name: 'Aircraft Launch and Recovery Officer'},
  { name: 'Aircraft Launch Specialist'},
  { name: 'Aircraft Mechanics OR Aircraft Service Technician'},
  { name: 'Aircraft Rigging Assembler'},
  { name: 'Aircraft Structure Assemblers'},
  { name: 'Airfield Operations Specialist'},
  { name: 'Airframe Mechanic'},
  { name: 'Airline Pilot OR Copilot OR Flight Engineer'},
  { name: 'Algorithm Developer'},
  { name: 'Alteration Tailor'},
  { name: 'Ambulance Driver'},
  { name: 'Amusement Attendant'},
  { name: 'Anesthesiologist'},
  { name: 'Animal Breeder'},
  { name: 'Animal Care Workers'},
  { name: 'Animal Control Worker'},
  { name: 'Animal Husbandry Worker'},
  { name: 'Animal Scientist'},
  { name: 'Animal Trainer'},
  { name: 'Annealing Machine Operator'},
  { name: 'Announcer'},
  { name: 'Answering Service'},
  { name: 'Anthropologist'},
  { name: 'Anthropologist OR Archeologist'},
  { name: 'Anthropology Teacher'},
  { name: 'Appliance Repairer'},
  { name: 'Arbitrator'},
  { name: 'Archeologist'},
  { name: 'Architect'},
  { name: 'Architectural Drafter'},
  { name: 'Architectural Drafter OR Civil Drafter'},
  { name: 'Architecture Teacher'},
  { name: 'Archivist'},
  { name: 'Armored Assault Vehicle Crew Member'},
  { name: 'Armored Assault Vehicle Officer'},
  { name: 'Art Director'},
  { name: 'Art Teacher'},
  { name: 'Artillery Officer'},
  { name: 'Artillery Crew Member'},
  { name: 'Artist'},
  { name: 'Assembler'},
  { name: 'Assessor'},
  { name: 'Astronomer'},
  { name: 'Athletes and Sports Competitor'},
  { name: 'Athletic Trainer'},
  { name: 'Atmospheric and Space Scientist'},
  { name: 'Audio and Video Equipment Technician'},
  { name: 'Audiologist'},
  { name: 'Audio-Visual Collections Specialist'},
  { name: 'Auditor'},
  { name: 'Auditor'},
  { name: 'Automatic Teller Machine Servicer'},
  { name: 'Automotive Body Repairer'},
  { name: 'Automotive Glass Installers'},
  { name: 'Automotive Master Mechanic'},
  { name: 'Automotive Mechanic'},
  { name: 'Automotive Specialty Technician'},
  { name: 'Automotive Technician'},
  { name: 'Auxiliary Equipment Operator'},
  { name: 'Aviation Inspector'},
  { name: 'Avionics Technician'},
  { name: 'Bailiff'},
  { name: 'Baker'},
  { name: 'Barber'},
  { name: 'Bartender'},
  { name: 'Bartender Helper'},
  { name: 'Battery Repairer'},
  { name: 'Bellhop'},
  { name: 'Bench Jeweler'},
  { name: 'Benefits Specialist'},
  { name: 'Bicycle Repairer'},
  { name: 'Bill and Account Collector'},
  { name: 'Bindery Machine Operator'},
  { name: 'Bindery Worker'},
  { name: 'Biochemist'},
  { name: 'Biochemist or Biophysicist'},
  { name: 'Biological Science Teacher'},
  { name: 'Biological Scientist'},
  { name: 'Biological Technician'},
  { name: 'Biologist'},
  { name: 'Biomedical Engineer'},
  { name: 'Biophysicist'},
  { name: 'Board Of Directors'},
  { name: 'Boat Builder and Shipwright'},
  { name: 'Boiler Operator'},
  { name: 'Boilermaker'},
  { name: 'Bookbinder'},
  { name: 'Bookkeeper'},
  { name: 'Brake Machine Setter'},
  { name: 'Brattice Builder'},
  { name: 'Brazer'},
  { name: 'Brazing Machine Operator'},
  { name: 'Brickmason'},
  { name: 'Bridge Tender OR Lock Tender'},
  { name: 'Broadcast News Analyst'},
  { name: 'Broadcast Technician'},
  { name: 'Brokerage Clerk'},
  { name: 'Budget Analyst'},
  { name: 'Buffing and Polishing Operator'},
  { name: 'Building Cleaning Worker'},
  { name: 'Building Inspector'},
  { name: 'Bulldozer Operator'},
  { name: 'Bus Driver'},
  { name: 'Business Development Manager'},
  { name: 'Business Manager'},
  { name: 'Business Operations Specialist'},
  { name: 'Business Teacher'},
  { name: 'Butcher'},
  { name: 'Buyer'},
  { name: 'Cabinetmaker'},
  { name: 'Cafeteria Cook'},
  { name: 'Calibration Technician OR Instrumentation Technician'},
  { name: 'Camera Operator'},
  { name: 'Camera Repairer'},
  { name: 'Captain'},
  { name: 'Caption Writer'},
  { name: 'Cardiovascular Technologist'},
  { name: 'Career Counselor'},
  { name: 'Carpenter'},
  { name: 'Carpenter Assembler and Repairer'},
  { name: 'Carpet Installer'},
  { name: 'Cartographer'},
  { name: 'Cartoonist'},
  { name: 'Carver'},
  { name: 'Cashier'},
  { name: 'Casting Machine Operator'},
  { name: 'Casting Machine Set-Up Operator'},
  { name: 'ccc'},
  { name: 'Ceiling Tile Installer'},
  { name: 'Cement Mason and Concrete Finisher'},
  { name: 'Central Office'},
  { name: 'Central Office and PBX Installers'},
  { name: 'Central Office Operator'},
  { name: 'CEO'},
  { name: 'CFO'},
  { name: 'Chef'},
  { name: 'Chemical Engineer'},
  { name: 'Chemical Equipment Controller'},
  { name: 'Chemical Equipment Operator'},
  { name: 'Chemical Equipment Tender'},
  { name: 'Chemical Plant Operator'},
  { name: 'Chemical Technician'},
  { name: 'Chemist'},
  { name: 'Chemistry Teacher'},
  { name: 'Child Care'},
  { name: 'Child Care Worker'},
  { name: 'Chiropractor'},
  { name: 'Choreographer'},
  { name: 'City'},
  { name: 'City Planning Aide'},
  { name: 'Civil Drafter'},
  { name: 'Civil Engineer'},
  { name: 'Civil Engineering Technician'},
  { name: 'Claims Adjuster'},
  { name: 'Claims Examiner'},
  { name: 'Claims Taker'},
  { name: 'Cleaners of Vehicles'},
  { name: 'Clergy'},
  { name: 'Clerk'},
  { name: 'Clinical Laboratory Technician'},
  { name: 'Clinical Psychologist'},
  { name: 'Clinical School Psychologist'},
  { name: 'Coaches and Scout'},
  { name: 'Coating Machine Operator'},
  { name: 'Coil Winders'},
  { name: 'Command Control Center Officer'},
  { name: 'Command Control Center Specialist'},
  { name: 'Commercial and Industrial Designer'},
  { name: 'Commercial Diver'},
  { name: 'Commercial Pilot'},
  { name: 'Communication Equipment Repairer'},
  { name: 'Communication Equipment Worker'},
  { name: 'Communications Equipment Operator'},
  { name: 'Communications Teacher'},
  { name: 'Community Service Manager'},
  { name: 'Compacting Machine Operator'},
  { name: 'Compensation and Benefits Manager'},
  { name: 'Compliance Officers'},
  { name: 'Composer'},
  { name: 'Computer'},
  { name: 'Computer Hardware Engineer'},
  { name: 'Computer Operator'},
  { name: 'Computer Programmer'},
  { name: 'Computer Repairer'},
  { name: 'Computer Science Teacher'},
  { name: 'Computer Scientist'},
  { name: 'Computer Security Specialist'},
  { name: 'Computer Software Engineer'},
  { name: 'Computer Specialist'},
  { name: 'Computer Support Specialist'},
  { name: 'Computer Systems Analyst'},
  { name: 'Computer-Controlled Machine Tool Operator'},
  { name: 'Concierge'},
  { name: 'Conservation Scientist'},
  { name: 'Construction'},
  { name: 'Construction Carpenter'},
  { name: 'Construction Driller'},
  { name: 'Construction Equipment Operator'},
  { name: 'Construction Laborer'},
  { name: 'Construction Manager'},
  { name: 'Continuous Mining Machine Operator'},
  { name: 'Control Valve Installer'},
  { name: 'Conveyor Operator'},
  { name: 'Cook'},
  { name: 'Cooling and Freezing Equipment Operator'},
  { name: 'Copy Machine Operator'},
  { name: 'Copy Writer'},
  { name: 'Coremaking Machine Operator'},
  { name: 'Coroner'},
  { name: 'Corporate Trainer'},
  { name: 'Correctional Officer'},
  { name: 'Correspondence Clerk'},
  { name: 'Cost Estimator'},
  { name: 'Costume Attendant'},
  { name: 'Counseling Psychologist'},
  { name: 'Counselor'},
  { name: 'Counsil'},
  { name: 'Courier'},
  { name: 'Court Clerk'},
  { name: 'Court Reporter'},
  { name: 'Craft Artist'},
  { name: 'Crane and Tower Operator'},
  { name: 'Creative Writer'},
  { name: 'Credit Checkers Clerk'},
  { name: 'Credit Analyst'},
  { name: 'Credit Authorizer'},
  { name: 'Credit Checker'},
  { name: 'Criminal Investigator'},
  { name: 'Crossing Guard'},
  { name: 'Crushing Grinding Machine Operator'},
  { name: 'CSI'},
  { name: 'CTO'},
  { name: 'Cultural Studies Teacher'},
  { name: 'Curator'},
  { name: 'Custom Tailor'},
  { name: 'Customer Service Representative'},
  { name: 'Cutting Machine Operator'},
  { name: 'Cutting Machine Operator'},
  { name: 'Dancer'},
  { name: 'Data Entry Operator'},
  { name: 'Data Processing Equipment Repairer'},
  { name: 'Database Administrator'},
  { name: 'Database Manager'},
  { name: 'Deburring Machine Operator'},
  { name: 'Decorator'},
  { name: 'Dental Assistant'},
  { name: 'Dental Hygienist'},
  { name: 'Dental Laboratory Technician'},
  { name: 'Dentist'},
  { name: 'Designer'},
  { name: 'Desktop Publisher'},
  { name: 'Detective'},
  { name: 'Diagnostic Medical Sonographer'},
  { name: 'Diamond Worker'},
  { name: 'Diesel Engine Specialist'},
  { name: 'Dietetic Technician'},
  { name: 'Director Of Business Development'},
  { name: 'Director Of Marketing'},
  { name: 'Director Of Social Media Marketing'},
  { name: 'Director Of Talent Acquisition'},
  { name: 'Director Religious Activities'},
  { name: 'Directory Assistance Operator'},
  { name: 'Dishwasher'},
  { name: 'Dispatcher'},
  { name: 'Distribution Manager'},
  { name: 'Door To Door Sales'},
  { name: 'Dot Etcher'},
  { name: 'Drafter'},
  { name: 'Dragline Operator'},
  { name: 'Dredge Operator'},
  { name: 'Drilling and Boring Machine Tool Setter'},
  { name: 'Driver-Sales Worker'},
  { name: 'Drycleaning Machine Operator'},
  { name: 'Drywall Ceiling Tile Installer'},
  { name: 'Drywall Installer'},
  { name: 'Earth Driller'},
  { name: 'Economics Teacher'},
  { name: 'Economist'},
  { name: 'Editor'},
  { name: 'Education Administrator'},
  { name: 'Education Teacher'},
  { name: 'Educational Counselor OR Vocationall Counselor'},
  { name: 'Educational Psychologist'},
  { name: 'Electric Meter Installer'},
  { name: 'Electric Motor Repairer'},
  { name: 'Electrical and Electronic Inspector and Tester'},
  { name: 'Electrical and Electronics Drafter'},
  { name: 'Electrical Drafter'},
  { name: 'Electrical Engineer'},
  { name: 'Electrical Engineering Technician'},
  { name: 'Electrical Parts Reconditioner'},
  { name: 'Electrical Power-Line Installer'},
  { name: 'Electrical Sales Representative'},
  { name: 'Electrician'},
  { name: 'Electrician'},
  { name: 'Electrolytic Plating Machine Operator'},
  { name: 'Electromechanical Equipment Assembler'},
  { name: 'Electro-Mechanical Technician'},
  { name: 'Electronic Drafter'},
  { name: 'Electronic Engineering Technician'},
  { name: 'Electronic Equipment Assembler'},
  { name: 'Electronic Masking System Operator'},
  { name: 'Electronics Engineer'},
  { name: 'Electronics Engineering Technician'},
  { name: 'Electrotyper'},
  { name: 'Elementary and Secondary School Administrators'},
  { name: 'Elementary School Teacher'},
  { name: 'Elevator Installer and Repairer'},
  { name: 'Eligibility Interviewer'},
  { name: 'Embalmer'},
  { name: 'Embossing Machine Operator'},
  { name: 'Emergency Management Specialist'},
  { name: 'Emergency Medical Technician and Paramedic'},
  { name: 'Employment Interviewer'},
  { name: 'Engine Assembler'},
  { name: 'Engineer'},
  { name: 'Engineering'},
  { name: 'Engineering Manager'},
  { name: 'Engineering Teacher'},
  { name: 'Engineering Technician'},
  { name: 'English Language Teacher'},
  { name: 'Engraver'},
  { name: 'Entertainer and Performer'},
  { name: 'Entertainment Attendant'},
  { name: 'Environmental Compliance Inspector'},
  { name: 'Environmental Engineer'},
  { name: 'Environmental Engineering Technician'},
  { name: 'Environmental Science Teacher'},
  { name: 'Environmental Science Technician'},
  { name: 'Environmental Scientist'},
  { name: 'Epidemiologist'},
  { name: 'Equal Opportunity Representative'},
  { name: 'Etcher'},
  { name: 'Etcher and Engraver'},
  { name: 'Event Planner'},
  { name: 'Excavating Machine Operator'},
  { name: 'Executive Secretary'},
  { name: 'Exhibit Designer'},
  { name: 'Explosives Expert'},
  { name: 'Extraction Worker'},
  { name: 'Extruding and Drawing Machine Operator'},
  { name: 'Extruding Machine Operator'},
  { name: 'Fabric Mender'},
  { name: 'Fabric Pressers'},
  { name: 'Farm and Home Management Advisor'},
  { name: 'Farm Equipment Mechanic'},
  { name: 'Farm Labor Contractor'},
  { name: 'Farmer'},
  { name: 'Farmworker'},
  { name: 'Fashion Designer'},
  { name: 'Fashion Model'},
  { name: 'Fast Food Cook'},
  { name: 'Fence Erector'},
  { name: 'Fiber Product Cutting Machine Operator'},
  { name: 'Fiberglass Laminator and Fabricator'},
  { name: 'File Clerk'},
  { name: 'Film Laboratory Technician'},
  { name: 'Financial Analyst'},
  { name: 'Financial Examiner'},
  { name: 'Financial Manager'},
  { name: 'Financial Services Sales Agent'},
  { name: 'Financial Specialist'},
  { name: 'Fire Fighter'},
  { name: 'Fire Inspector'},
  { name: 'Fire Investigator'},
  { name: 'Fire-Prevention Engineer'},
  { name: 'Fish Game Warden'},
  { name: 'Fish Hatchery Manager'},
  { name: 'Fishery Worker'},
  { name: 'Fishing OR Forestry Supervisor'},
  { name: 'Fitness Trainer'},
  { name: 'Fitter'},
  { name: 'Flight Attendant'},
  { name: 'Floor Finisher'},
  { name: 'Floor Layer'},
  { name: 'Floral Designer'},
  { name: 'Food Batchmaker'},
  { name: 'Food Cooking Machine Operators'},
  { name: 'Food Preparation'},
  { name: 'Food Preparation and Serving Worker'},
  { name: 'Food Preparation Worker'},
  { name: 'Food Science Technician'},
  { name: 'Food Scientists and Technologist'},
  { name: 'Food Servers'},
  { name: 'Food Service Manager'},
  { name: 'Food Tobacco Roasting'},
  { name: 'Foreign Language Teacher'},
  { name: 'Forensic Investigator'},
  { name: 'Forensic Science Technician'},
  { name: 'Forest and Conservation Technician'},
  { name: 'Forest and Conservation Worker'},
  { name: 'Forest Fire Fighter'},
  { name: 'Forest Fire Fighting Supervisor'},
  { name: 'Forest Fire Inspector'},
  { name: 'Forester'},
  { name: 'Forestry Conservation Science Teacher'},
  { name: 'Forging Machine Setter'},
  { name: 'Forming Machine Operator'},
  { name: 'Forming Machine Operator'},
  { name: 'Foundry Mold and Coremaker'},
  { name: 'Fraud Investigator'},
  { name: 'Freight Agent'},
  { name: 'Freight and Material Mover'},
  { name: 'Freight Inspector'},
  { name: 'Funeral Attendant'},
  { name: 'Funeral Director'},
  { name: 'Furnace Operator'},
  { name: 'Furniture Finisher'},
  { name: 'Gaming Cage Worker'},
  { name: 'Gaming Dealer'},
  { name: 'Gaming Manager'},
  { name: 'Gaming Service Worker'},
  { name: 'Gaming Supervisor'},
  { name: 'Gaming Surveillance Officer'},
  { name: 'Garment'},
  { name: 'Gas Appliance Repairer'},
  { name: 'Gas Compressor Operator'},
  { name: 'Gas Distribution Plant Operator'},
  { name: 'Gas Plant Operator'},
  { name: 'Gas Processing Plant Operator'},
  { name: 'Gas Pumping Station Operator'},
  { name: 'Gas Pumping Station Operator'},
  { name: 'Gauger'},
  { name: 'GED Teacher'},
  { name: 'General Farmworker'},
  { name: 'General Manager'},
  { name: 'General Practitioner'},
  { name: 'Geographer'},
  { name: 'Geography Teacher'},
  { name: 'Geological Data Technician'},
  { name: 'Geological Sample Test Technician'},
  { name: 'Geologist'},
  { name: 'Geoscientists'},
  { name: 'Glass Blower'},
  { name: 'Glass Cutting Machine Operator'},
  { name: 'Glazier'},
  { name: 'Gluing Machine Operator'},
  { name: 'Government'},
  { name: 'Government Property Inspector'},
  { name: 'Government Service Executive'},
  { name: 'Graduate Teaching Assistant'},
  { name: 'Graphic Designer'},
  { name: 'Grinder OR Polisher'},
  { name: 'Grinding Machine Operator'},
  { name: 'Grips'},
  { name: 'Grounds Maintenance Worker'},
  { name: 'Hairdresser OR Cosmetologist'},
  { name: 'Hand Trimmer'},
  { name: 'Hand Presser'},
  { name: 'Hand Sewer'},
  { name: 'Hazardous Materials Removal Worker'},
  { name: 'Head Nurse'},
  { name: 'Health Educator'},
  { name: 'Health Practitioner'},
  { name: 'Health Services Manager'},
  { name: 'Health Specialties Teacher'},
  { name: 'Health Technologist'},
  { name: 'Healthcare'},
  { name: 'Healthcare Practitioner'},
  { name: 'Healthcare Support Worker'},
  { name: 'Heat Treating Equipment Operator'},
  { name: 'Heaters'},
  { name: 'Heating and Air Conditioning Mechanic'},
  { name: 'Heating Equipment Operator'},
  { name: 'Heavy Equipment Mechanic'},
  { name: 'Highway Maintenance Worker'},
  { name: 'Highway Patrol Pilot'},
  { name: 'Historian'},
  { name: 'History Teacher'},
  { name: 'Hoist and Winch Operator'},
  { name: 'Home'},
  { name: 'Home Appliance Installer'},
  { name: 'Home Appliance Repairer'},
  { name: 'Home Economics Teacher'},
  { name: 'Home Entertainment Equipment Installer'},
  { name: 'Home Health Aide'},
  { name: 'Homeland Security'},
  { name: 'Horticultural Worker'},
  { name: 'Host and Hostess'},
  { name: 'Hotel Desk Clerk'},
  { name: 'House Cleaner'},
  { name: 'Housekeeper'},
  { name: 'Housekeeping Supervisor'},
  { name: 'HR Manager'},
  { name: 'HR Specialist'},
  { name: 'Human Resource Director'},
  { name: 'Human Resource Manager'},
  { name: 'Human Resources Assistant'},
  { name: 'Human Resources Manager'},
  { name: 'Human Resources Specialist'},
  { name: 'Hunter and Trapper'},
  { name: 'HVAC Mechanic'},
  { name: 'Hydrologist'},
  { name: 'Illustrator'},
  { name: 'Immigration Inspector OR Customs Inspector'},
  { name: 'Industrial Engineer'},
  { name: 'Industrial Engineering Technician'},
  { name: 'Industrial Equipment Maintenance'},
  { name: 'Industrial Machinery Mechanic'},
  { name: 'Industrial Production Manager'},
  { name: 'Industrial Safety Engineer'},
  { name: 'Industrial-Organizational Psychologist'},
  { name: 'Infantry'},
  { name: 'Infantry Officer'},
  { name: 'Information Systems Manager'},
  { name: 'Inspector'},
  { name: 'Installation and Repair Technician'},
  { name: 'Instructional Coordinator'},
  { name: 'Instrument Sales Representative'},
  { name: 'Insulation Installer'},
  { name: 'Insulation Worker'},
  { name: 'Insurance Investigator'},
  { name: 'Insurance Appraiser'},
  { name: 'Insurance Claims Clerk'},
  { name: 'Insurance Policy Processing Clerk'},
  { name: 'Insurance Sales Agent'},
  { name: 'Insurance Underwriter'},
  { name: 'Interaction Designer'},
  { name: 'Interior Designer'},
  { name: 'Internist'},
  { name: 'Interpreter OR Translator'},
  { name: 'Interviewer'},
  { name: 'Irradiated-Fuel Handler'},
  { name: 'Janitor'},
  { name: 'Janitorial Supervisor'},
  { name: 'Jeweler'},
  { name: 'Jewelry Model OR Mold Makers'},
  { name: 'Job Printer'},
  { name: 'Judge'},
  { name: 'Keyboard Instrument Repairer and Tuner'},
  { name: 'Kindergarten Teacher'},
  { name: 'Landscape Architect'},
  { name: 'Landscape Artist'},
  { name: 'Landscaper'},
  { name: 'Landscaping'},
  { name: 'Lathe Operator'},
  { name: 'Laundry OR Dry-Cleaning Worker'},
  { name: 'Law Clerk'},
  { name: 'Law Enforcement Teacher'},
  { name: 'Law Teacher'},
  { name: 'Lawn Service Manager'},
  { name: 'Lawyer'},
  { name: 'Lay-Out Worker'},
  { name: 'Legal Secretary'},
  { name: 'Legal Support Worker'},
  { name: 'Legislator'},
  { name: 'Letterpress Setters Operator'},
  { name: 'Librarian'},
  { name: 'Library Assistant'},
  { name: 'Library Science Teacher'},
  { name: 'Library Technician'},
  { name: 'Library Worker'},
  { name: 'License Clerk'},
  { name: 'Licensed Practical Nurse'},
  { name: 'Licensing Examiner and Inspector'},
  { name: 'Life Science Technician'},
  { name: 'Life Scientists'},
  { name: 'Lifeguard'},
  { name: 'Loading Machine Operator'},
  { name: 'Loan Counselor'},
  { name: 'Loan Interviewer'},
  { name: 'Loan Officer'},
  { name: 'Locker Room Attendant'},
  { name: 'Locksmith'},
  { name: 'Locomotive Engineer'},
  { name: 'Locomotive Firer'},
  { name: 'Lodging Manager'},
  { name: 'Log Grader and Scaler'},
  { name: 'Logging Equipment Operator'},
  { name: 'Logging Supervisor'},
  { name: 'Logging Tractor Operator'},
  { name: 'Logging Worker'},
  { name: 'Logistician'},
  { name: 'Machine Feeder'},
  { name: 'Machine Operator'},
  { name: 'Machine Tool Operator'},
  { name: 'Machinery Maintenance'},
  { name: 'Machinist'},
  { name: 'Maid'},
  { name: 'Mail Clerk'},
  { name: 'Mail Machine Operator'},
  { name: 'Maintenance and Repair Worker'},
  { name: 'Maintenance Equipment Operator'},
  { name: 'Maintenance Supervisor'},
  { name: 'Maintenance Worker'},
  { name: 'Makeup Artists'},
  { name: 'Management Analyst'},
  { name: 'Manager'},
  { name: 'Manager of Air Crew'},
  { name: 'Manager of Food Preparation'},
  { name: 'Manager of Weapons Specialists'},
  { name: 'Manager Tactical Operations'},
  { name: 'Manicurists'},
  { name: 'Manufactured Building Installer'},
  { name: 'Manufacturing Sales Representative'},
  { name: 'Mapping Technician'},
  { name: 'MARCOM Director'},
  { name: 'MARCOM Manager'},
  { name: 'Marine Architect'},
  { name: 'Marine Cargo Inspector'},
  { name: 'Marine Engineer'},
  { name: 'Marine Oiler'},
  { name: 'Market Research Analyst'},
  { name: 'Marketing Manager'},
  { name: 'Marketing VP'},
  { name: 'Marking Clerk'},
  { name: 'Marking Machine Operator'},
  { name: 'Marriage and Family Therapist'},
  { name: 'Massage Therapist'},
  { name: 'Material Movers'},
  { name: 'Material Moving Worker'},
  { name: 'Materials Engineer'},
  { name: 'Materials Inspector'},
  { name: 'Materials Scientist'},
  { name: 'Mathematical Science Teacher'},
  { name: 'Mathematical Scientist'},
  { name: 'Mathematical Technician'},
  { name: 'Mathematician'},
  { name: 'Meat Packer'},
  { name: 'Mechanical Door Repairer'},
  { name: 'Mechanical Drafter'},
  { name: 'Mechanical Engineer'},
  { name: 'Mechanical Engineering Technician'},
  { name: 'Mechanical Equipment Sales Representative'},
  { name: 'Mechanical Inspector'},
  { name: 'Media and Communication Worker'},
  { name: 'Medical Appliance Technician'},
  { name: 'Medical Assistant'},
  { name: 'Medical Equipment Preparer'},
  { name: 'Medical Equipment Repairer'},
  { name: 'Medical Laboratory Technologist'},
  { name: 'Medical Records Technician'},
  { name: 'Medical Sales Representative'},
  { name: 'Medical Scientists'},
  { name: 'Medical Secretary'},
  { name: 'Medical Technician'},
  { name: 'Medical Transcriptionist'},
  { name: 'Mental Health Counselor'},
  { name: 'Merchandise Displayer OR Window Trimmer'},
  { name: 'Metal Fabricator'},
  { name: 'Metal Molding Operator'},
  { name: 'Metal Pourer and Caster'},
  { name: 'Metal Worker'},
  { name: 'Metal-Refining Furnace Operator'},
  { name: 'Meter Mechanic'},
  { name: 'Microbiologist'},
  { name: 'Middle School Teacher'},
  { name: 'Military Officer'},
  { name: 'Milling Machine Operator'},
  { name: 'Millwright'},
  { name: 'Mine Cutting Machine Operator'},
  { name: 'Mining Engineer OR Geological Engineer'},
  { name: 'Mining Machine Operator'},
  { name: 'Mixing and Blending Machine Operator'},
  { name: 'Model Maker'},
  { name: 'Mold Maker'},
  { name: 'Molder'},
  { name: 'Molding and Casting Worker'},
  { name: 'Molding Machine Operator'},
  { name: 'Motion Picture Projectionist'},
  { name: 'Motor Vehicle Inspector'},
  { name: 'Motor Vehicle Operator'},
  { name: 'Motorboat Mechanic'},
  { name: 'Motorboat Operator'},
  { name: 'Motorcycle Mechanic'},
  { name: 'Movers'},
  { name: 'Movie Director oR Theatre Director'},
  { name: 'Multi-Media Artist'},
  { name: 'Multiple Machine Tool Setter'},
  { name: 'Municipal Clerk'},
  { name: 'Municipal Court Clerk'},
  { name: 'Municipal Fire Fighter'},
  { name: 'Municipal Fire Fighting Supervisor'},
  { name: 'Museum Conservator'},
  { name: 'Music Arranger and Orchestrator'},
  { name: 'Music Composer'},
  { name: 'Music Director'},
  { name: 'Musical Instrument Tuner'},
  { name: 'Musician'},
  { name: 'Musician OR Singer'},
  { name: 'Natural Sciences Manager'},
  { name: 'Naval Architects'},
  { name: 'Network Admin OR Computer Systems Administrator'},
  { name: 'Network Systems Analyst'},
  { name: 'New Accounts Clerk'},
  { name: 'Night Security Guard'},
  { name: 'Night Shift'},
  { name: 'Nonfarm Animal Caretaker'},
  { name: 'Nuclear Engineer'},
  { name: 'Nuclear Equipment Operation Technician'},
  { name: 'Nuclear Medicine Technologist'},
  { name: 'Nuclear Monitoring Technician'},
  { name: 'Nuclear Power Reactor Operator'},
  { name: 'Nuclear Technician'},
  { name: 'Numerical Control Machine Tool Operator'},
  { name: 'Numerical Tool Programmer OR Process Control Programmer'},
  { name: 'Nursery Manager'},
  { name: 'Nursery Worker'},
  { name: 'Nursing Aide'},
  { name: 'Nursing Instructor'},
  { name: 'Nutritionist'},
  { name: 'Obstetrician'},
  { name: 'Occupational Health Safety Specialist'},
  { name: 'Occupational Health Safety Technician'},
  { name: 'Occupational Therapist'},
  { name: 'Occupational Therapist Aide'},
  { name: 'Occupational Therapist Assistant'},
  { name: 'Office and Administrative Support Worker'},
  { name: 'Office Clerk'},
  { name: 'Office Machine and Cash Register Servicer'},
  { name: 'Office Machine Operator'},
  { name: 'Offset Lithographic Press Operator'},
  { name: 'Oil and gas Operator'},
  { name: 'Oil Service Unit Operator'},
  { name: 'Online Marketing Analyst'},
  { name: 'Operating Engineer'},
  { name: 'Operations Research Analyst'},
  { name: 'Ophthalmic Laboratory Technician'},
  { name: 'Optical Instrument Assembler'},
  { name: 'Opticians'},
  { name: 'Optometrist'},
  { name: 'Oral Surgeon'},
  { name: 'Order Clerk'},
  { name: 'Order Filler'},
  { name: 'Order Filler OR Stock Clerk'},
  { name: 'Organizational Development Manager'},
  { name: 'Orthodontist'},
  { name: 'Orthotist OR Prosthetist'},
  { name: 'Outdoor Power Equipment Mechanic'},
  { name: 'Packaging Machine Operator'},
  { name: 'Packer and Packager'},
  { name: 'Painter'},
  { name: 'Painter and Illustrator'},
  { name: 'Painting Machine Operator'},
  { name: 'Pantograph Engraver'},
  { name: 'Paper Goods Machine Operator'},
  { name: 'Paperhanger'},
  { name: 'Paralegal'},
  { name: 'Park Naturalist'},
  { name: 'Parking Enforcement Worker'},
  { name: 'Parking Lot Attendant'},
  { name: 'Parts Salesperson'},
  { name: 'Paste-Up Worker'},
  { name: 'Pastry Chef'},
  { name: 'Patrol Officer'},
  { name: 'Patternmaker'},
  { name: 'Paving Equipment Operator'},
  { name: 'Payroll Clerk'},
  { name: 'Pediatricians'},
  { name: 'Percussion Instrument Repairer'},
  { name: 'Personal Care Worker'},
  { name: 'Personal Financial Advisor'},
  { name: 'Personal Home Care Aide'},
  { name: 'Personal Service Worker'},
  { name: 'Personal Trainer'},
  { name: 'Personnel Recruiter'},
  { name: 'Pest Control Worker'},
  { name: 'Pesticide Sprayer'},
  { name: 'Petroleum Engineer'},
  { name: 'Petroleum Pump Operator'},
  { name: 'Petroleum Pump System Operator'},
  { name: 'Petroleum Technician'},
  { name: 'Pewter Caster'},
  { name: 'Pharmaceutical Sales Representative'},
  { name: 'Pharmacist'},
  { name: 'Pharmacy Aide'},
  { name: 'Pharmacy Technician'},
  { name: 'Philosophy and Religion Teacher'},
  { name: 'Photoengraver'},
  { name: 'Photoengraving Machine Operator'},
  { name: 'Photographer'},
  { name: 'Photographic Restorer'},
  { name: 'Photographic Developer'},
  { name: 'Photographic Process Worker'},
  { name: 'Photographic Processing Machine Operator'},
  { name: 'Photographic Reproduction Technician'},
  { name: 'Physical Scientist'},
  { name: 'Physical Therapist'},
  { name: 'Physical Therapist Aide'},
  { name: 'Physical Therapist Assistant'},
  { name: 'Physician'},
  { name: 'Physician Assistant'},
  { name: 'Physicist'},
  { name: 'Physics Teacher'},
  { name: 'Pile-Driver Operator'},
  { name: 'Pipe Fitter'},
  { name: 'Pipefitter'},
  { name: 'Pipelayer'},
  { name: 'Pipelaying Fitter'},
  { name: 'Plant and System Operator'},
  { name: 'Plant Scientist'},
  { name: 'Plasterer OR Stucco Mason'},
  { name: 'Plastic Molding Machine Operator'},
  { name: 'Plate Finisher'},
  { name: 'Platemaker'},
  { name: 'Plating Machine Operator'},
  { name: 'Plating Operator'},
  { name: 'Plating Operator OR Coating Machine Operator'},
  { name: 'Plumber'},
  { name: 'Plumber OR Pipefitter OR Steamfitter'},
  { name: 'Podiatrist'},
  { name: 'Poet OR Lyricist'},
  { name: 'Police and Sheriffs Patrol Officer'},
  { name: 'Police Detective'},
  { name: 'Police Identification OR Records Officer'},
  { name: 'Political Science Teacher'},
  { name: 'Political Scientist'},
  { name: 'Portable Power Tool Repairer'},
  { name: 'Postal Clerk'},
  { name: 'Postal Service Clerk'},
  { name: 'Postal Service Mail Carrier'},
  { name: 'Postal Service Mail Sorter'},
  { name: 'Postmasters'},
  { name: 'Postsecondary Education Administrators'},
  { name: 'Postsecondary Teacher'},
  { name: 'Potter'},
  { name: 'Poultry Cutter'},
  { name: 'Power Distributors OR Dispatcher'},
  { name: 'Power Generating Plant Operator'},
  { name: 'Power Plant Operator'},
  { name: 'PR Manager'},
  { name: 'Precious Stone Worker'},
  { name: 'Precision Aircraft Systems Assemblers'},
  { name: 'Precision Devices Inspector'},
  { name: 'Precision Dyer'},
  { name: 'Precision Etcher and Engraver'},
  { name: 'Precision Instrument Repairer'},
  { name: 'Precision Lens Grinders and Polisher'},
  { name: 'Precision Mold and Pattern Caster'},
  { name: 'Precision Pattern and Die Caster'},
  { name: 'Precision Printing Worker'},
  { name: 'Prepress Technician'},
  { name: 'Preschool Education Administrators'},
  { name: 'Preschool Teacher'},
  { name: 'Press Machine Setter, Operator'},
  { name: 'Pressing Machine Operator'},
  { name: 'Pressure Vessel Inspector'},
  { name: 'Printing Machine Operator'},
  { name: 'Printing Press Machine Operator'},
  { name: 'Private Detective and Investigator'},
  { name: 'Private Household Cook'},
  { name: 'Private Sector Executive'},
  { name: 'Probation Officers and Correctional Treatment Specialist'},
  { name: 'Procurement Clerk'},
  { name: 'Producer'},
  { name: 'Producers and Director'},
  { name: 'Product Management Leader'},
  { name: 'Product Promoter'},
  { name: 'Product Safety Engineer'},
  { name: 'Product Specialist'},
  { name: 'Production Control Manager'},
  { name: 'Production Helper'},
  { name: 'Production Inspector'},
  { name: 'Production Laborer'},
  { name: 'Production Manager'},
  { name: 'Production Planner'},
  { name: 'Production Planning'},
  { name: 'Production Worker'},
  { name: 'Professional Photographer'},
  { name: 'Professor'},
  { name: 'Program Director'},
  { name: 'Project Manager'},
  { name: 'Proofreaders and Copy Marker'},
  { name: 'Prosthodontist'},
  { name: 'Protective Service Worker'},
  { name: 'Protective Service Worker'},
  { name: 'Psychiatric Aide'},
  { name: 'Psychiatric Technician'},
  { name: 'Psychiatrist'},
  { name: 'Psychologist'},
  { name: 'Psychology Teacher'},
  { name: 'Public Health Social Worker'},
  { name: 'Public Relations Manager'},
  { name: 'Public Relations Specialist'},
  { name: 'Public Transportation Inspector'},
  { name: 'Pump Operators'},
  { name: 'Punching Machine Setters'},
  { name: 'Purchasing Agent'},
  { name: 'Purchasing Manager'},
  { name: 'Radar Technician'},
  { name: 'Radiation Therapist'},
  { name: 'Radio and Television Announcer'},
  { name: 'Radio Mechanic'},
  { name: 'Radio Operator'},
  { name: 'Radiologic Technician'},
  { name: 'Radiologic Technologist'},
  { name: 'Radiologic Technologist and Technician'},
  { name: 'Rail Car Repairer'},
  { name: 'Rail Transportation Worker'},
  { name: 'Rail Yard Engineer'},
  { name: 'Railroad Conductors'},
  { name: 'Railroad Inspector'},
  { name: 'Railroad Switch Operator'},
  { name: 'Railroad Yard Worker'},
  { name: 'Range Manager'},
  { name: 'Real Estate Appraiser'},
  { name: 'Real Estate Association Manager'},
  { name: 'Real Estate Broker'},
  { name: 'Real Estate Sales Agent'},
  { name: 'Receptionist and Information Clerk'},
  { name: 'Record Clerk'},
  { name: 'Recordkeeping Clerk'},
  { name: 'Recreation and Fitness Studies Teacher'},
  { name: 'Recreation Worker'},
  { name: 'Recreational Therapist'},
  { name: 'Recreational Vehicle Service Technician'},
  { name: 'Recruiter'},
  { name: 'Recyclable Material Collector'},
  { name: 'Refinery Operator'},
  { name: 'Refractory Materials Repairer'},
  { name: 'Refrigeration Mechanic'},
  { name: 'Registered Nurse'},
  { name: 'Rehabilitation Counselor'},
  { name: 'Religious Worker'},
  { name: 'Rental Clerk'},
  { name: 'Reporters OR Correspondent'},
  { name: 'Reservation Agent OR Transportation Ticket Agent'},
  { name: 'Residential Advisor'},
  { name: 'Respiratory Therapist'},
  { name: 'Respiratory Therapy Technician'},
  { name: 'Restaurant Cook'},
  { name: 'Retail Sales person'},
  { name: 'Retail Salesperson'},
  { name: 'Rigger'},
  { name: 'RN'},
  { name: 'Rock Splitter'},
  { name: 'Rolling Machine Setter'},
  { name: 'Roof Bolters Mining'},
  { name: 'Roofer'},
  { name: 'Rotary Drill Operator'},
  { name: 'Rough Carpenter'},
  { name: 'Roustabouts'},
  { name: 'Safety Engineer'},
  { name: 'Sailor'},
  { name: 'Sales and Related Workers'},
  { name: 'Sales Engineer'},
  { name: 'Sales Manager'},
  { name: 'Sales Person'},
  { name: 'Sales Representative'},
  { name: 'Sawing Machine Operator'},
  { name: 'Sawing Machine Setter'},
  { name: 'Sawing Machine Tool Setter'},
  { name: 'Scanner Operator'},
  { name: 'School Bus Driver'},
  { name: 'School Social Worker'},
  { name: 'Scientific Photographer'},
  { name: 'Screen Printing Machine Operator'},
  { name: 'Sculptor'},
  { name: 'Secondary School Teacher'},
  { name: 'Secretary'},
  { name: 'Securities Sales Agent'},
  { name: 'Security Guard'},
  { name: 'Security Systems Installer OR Fire Alarm Systems Installer'},
  { name: 'Segmental Paver'},
  { name: 'Self-Enrichment Education Teacher'},
  { name: 'Semiconductor Processor'},
  { name: 'Separating Machine Operators'},
  { name: 'Septic Tank Servicer'},
  { name: 'Service Station Attendant'},
  { name: 'Set and Exhibit Designer'},
  { name: 'Set Designer'},
  { name: 'Sewing Machine Operator'},
  { name: 'Shampooer'},
  { name: 'Shear Machine Set-Up Operator'},
  { name: 'Sheet Metal Worker'},
  { name: 'Sheriff'},
  { name: 'Ship Captain'},
  { name: 'Ship Carpenter and Joiner'},
  { name: 'Ship Engineer'},
  { name: 'Ship Mates'},
  { name: 'Ship Pilot'},
  { name: 'Shipping and Receiving Clerk'},
  { name: 'Shoe and Leather Repairer'},
  { name: 'Shoe Machine Operators'},
  { name: 'Short Order Cook'},
  { name: 'Shuttle Car Operator'},
  { name: 'Signal Repairer OR Track Switch Repairer'},
  { name: 'Silversmith'},
  { name: 'Singer'},
  { name: 'Sketch Artist'},
  { name: 'Skin Care Specialist'},
  { name: 'Slot Key Person'},
  { name: 'Social and Human Service Assistant'},
  { name: 'Social Media Marketing Manager'},
  { name: 'Social Science Research Assistant'},
  { name: 'Social Sciences Teacher'},
  { name: 'Social Scientists'},
  { name: 'Social Service Specialists'},
  { name: 'Social Work Teacher'},
  { name: 'Social Worker'},
  { name: 'Sociologist'},
  { name: 'Sociology Teacher'},
  { name: 'Software Engineer'},
  { name: 'Soil Conservationist'},
  { name: 'Soil Scientist'},
  { name: 'Soil Scientist OR Plant Scientist'},
  { name: 'Solderer'},
  { name: 'Soldering Machine Setter'},
  { name: 'Sound Engineering Technician'},
  { name: 'Space Sciences Teacher'},
  { name: 'Special Education Teacher'},
  { name: 'Special Force'},
  { name: 'Special Forces Officer'},
  { name: 'Speech-Language Pathologist'},
  { name: 'Sports Book Writer'},
  { name: 'Spotters'},
  { name: 'Spraying Machine Operator'},
  { name: 'Staff Psychologist'},
  { name: 'State'},
  { name: 'Statement Clerk'},
  { name: 'Stationary Engineer'},
  { name: 'Stationary Engineer OR Boiler Operator'},
  { name: 'Statistical Assistant'},
  { name: 'Statistician'},
  { name: 'Steel Worker'},
  { name: 'Stevedore'},
  { name: 'Stock Broker'},
  { name: 'Stock Clerk'},
  { name: 'Stone Cutter'},
  { name: 'Stone Sawyer'},
  { name: 'Stonemason'},
  { name: 'Stonemason'},
  { name: 'Storage Manager OR Distribution Manager'},
  { name: 'Streetcar Operator'},
  { name: 'Stringed Instrument Repairer and Tuner'},
  { name: 'Stripper'},
  { name: 'Structural Iron and Steel Worker'},
  { name: 'Structural Metal Fabricator'},
  { name: 'Substance Abuse Counselor'},
  { name: 'Substance Abuse Social Worker'},
  { name: 'Substation Maintenance'},
  { name: 'Supervisor Correctional Officer'},
  { name: 'Supervisor Fire Fighting Worker'},
  { name: 'Supervisor of Customer Service'},
  { name: 'Supervisor of Police'},
  { name: 'Surgeon'},
  { name: 'Surgical Technologist'},
  { name: 'Survey Researcher'},
  { name: 'Surveying and Mapping Technician'},
  { name: 'Surveying Technician'},
  { name: 'Surveyor'},
  { name: 'Sys Admin'},
  { name: 'System Administrator'},
  { name: 'Tailor'},
  { name: 'Talent Acquisition Manager'},
  { name: 'Talent Director'},
  { name: 'Tank Car'},
  { name: 'Taper'},
  { name: 'Tax Examiner'},
  { name: 'Tax Preparer'},
  { name: 'Taxi Drivers and Chauffeur'},
  { name: 'Teacher'},
  { name: 'Teacher Assistant'},
  { name: 'Team Assembler'},
  { name: 'Technical Director'},
  { name: 'Technical Program Manager'},
  { name: 'Technical Specialist'},
  { name: 'Technical Writer'},
  { name: 'Telecommunications Equipment Installer'},
  { name: 'Telecommunications Facility Examiner'},
  { name: 'Telecommunications Line Installer'},
  { name: 'Telemarketer'},
  { name: 'Telephone Operator'},
  { name: 'Telephone Station Installer and Repairer'},
  { name: 'Teller'},
  { name: 'Terrazzo Workes and Finisher'},
  { name: 'Textile Cutting Machine Operator'},
  { name: 'Textile Dyeing Machine Operator'},
  { name: 'Textile Knitting Machine Operator'},
  { name: 'Textile Machine Operator'},
  { name: 'Textile Worker'},
  { name: 'Therapist'},
  { name: 'Ticket Agent'},
  { name: 'Tile Setter OR Marble Setter'},
  { name: 'Timing Device Assemblers'},
  { name: 'Tire Builder'},
  { name: 'Tire Changer'},
  { name: 'Title Abstractor'},
  { name: 'Title Examiner'},
  { name: 'Title Searcher'},
  { name: 'Tool and Die Maker'},
  { name: 'Tool Set-Up Operator'},
  { name: 'Tool Sharpener'},
  { name: 'Tour Guide'},
  { name: 'Tractor Operator'},
  { name: 'Tractor-Trailer Truck Driver'},
  { name: 'Traffic Technician'},
  { name: 'Train Crew'},
  { name: 'Trainer'},
  { name: 'Training Manager OR Development Manager'},
  { name: 'Transformer Repairer'},
  { name: 'Transit Police OR Railroad Police'},
  { name: 'Transportation and Material-Moving'},
  { name: 'Transportation Attendant'},
  { name: 'Transportation Equipment Maintenance'},
  { name: 'Transportation Equipment Painters'},
  { name: 'Transportation Inspector'},
  { name: 'Transportation Manager'},
  { name: 'Transportation Worker'},
  { name: 'Travel Agent'},
  { name: 'Travel Clerk'},
  { name: 'Travel Guide'},
  { name: 'Tree Trimmer'},
  { name: 'Truck Driver'},
  { name: 'TSA'},
  { name: 'Typesetter'},
  { name: 'Typesetting Machine Operator'},
  { name: 'Umpire and Referee'},
  { name: 'Underground Mining'},
  { name: 'University'},
  { name: 'Upholsterer'},
  { name: 'Urban Planner'},
  { name: 'User Experience Manager'},
  { name: 'User Experience Researcher'},
  { name: 'Usher'},
  { name: 'Utility Meter Reader'},
  { name: 'Valve Repairer OR Regulator Repairer'},
  { name: 'Vending Machine Servicer'},
  { name: 'Veterinarian'},
  { name: 'Veterinary Assistant OR Laboratory Animal Caretaker'},
  { name: 'Veterinary Technician'},
  { name: 'Vice President Of Human Resources'},
  { name: 'Vice President Of Marketing'},
  { name: 'Video Editor'},
  { name: 'Visual Designer'},
  { name: 'Vocational Education Teacher'},
  { name: 'Waiter'},
  { name: 'Waitress'},
  { name: 'Warehouse'},
  { name: 'Washing Equipment Operator'},
  { name: 'Waste Treatment Plant Operator'},
  { name: 'Watch Repairer'},
  { name: 'Weapons Specialists'},
  { name: 'Web Developer'},
  { name: 'Webmaster'},
  { name: 'Welder'},
  { name: 'Welder'},
  { name: 'Welder and Cutter'},
  { name: 'Welder-Fitter'},
  { name: 'Welding Machine Tender'},
  { name: 'Welding Machine Operator'},
  { name: 'Welding Machine Setter'},
  { name: 'Welfare Eligibility Clerk'},
  { name: 'Well and Core Drill Operator'},
  { name: 'Wellhead Pumper'},
  { name: 'Wholesale Buyer'},
  { name: 'Wind Instrument Repairer'},
  { name: 'Woodworker'},
  { name: 'Woodworking Machine Operator'},
  { name: 'Woodworking Machine Setter'},
  { name: 'Word Processors and Typist'},
  { name: 'Writer OR Author'},
  { name: 'Zoologists OR Wildlife Biologist'}
]

return { items }

}